export const MIN_PROFILE_NAME_LENGTH = 2;
export const MAX_PROFILE_NAME_LENGTH = 20;

export const MIN_PHONE_NUMBER_LENGTH = 2;
export const MAX_PHONE_NUMBER_LENGTH = 50;

export const MAX_SHARE_TEXT_LENGTH = 2000;

export const MIN_DISPLAY_NAME_LENGTH = 2;
export const MAX_DISPLAY_NAME_LENGTH = 20;
